# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

sylius_shop_partial_taxon:
    resource: "@SyliusLegacyBridgePlugin/config/routes/shop/partial/taxon.yml"
    prefix: /taxons

sylius_shop_partial_cart:
    resource: "@SyliusLegacyBridgePlugin/config/routes/shop/partial/cart.yml"
    prefix: /cart

sylius_shop_partial_product:
    resource: "@SyliusLegacyBridgePlugin/config/routes/shop/partial/product.yml"
    prefix: /products

sylius_shop_partial_product_review:
    resource: "@SyliusLegacyBridgePlugin/config/routes/shop/partial/product_review.yml"
    prefix: /products/{productId}/reviews

sylius_shop_partial_product_association:
    resource: "@SyliusLegacyBridgePlugin/config/routes/shop/partial/product_association.yml"
    prefix: /products/{productId}/associations
