imports:
    - { resource: "@SyliusLegacyBridgePlugin/config/events.yaml" }

sonata_block:
    default_contexts: ~

twig:
    globals:
        use_webpack: '%sylius_ui.use_webpack%'

liip_imagine:
    filter_sets:
        sylius_shop_product_tiny_thumbnail:
            filters:
                thumbnail: { size: [64, 64], mode: outbound }

framework:
    assets:
        packages:
            legacy.shop:
                json_manifest_path: '%kernel.project_dir%/public/build/legacy/shop/manifest.json'

webpack_encore:
    output_path: '%kernel.project_dir%/public/build/default'
    builds:      
        legacy.shop: '%kernel.project_dir%/public/build/legacy/shop'
