sylius_grid:
    templates:
        action:
            pay: "@SyliusShop/Account/Order/Grid/Action/_pay_deprecated.html.twig"
            shop_show: "@SyliusShop/Grid/Action/show.html.twig"
            shop_pay: "@SyliusShop/Account/Order/Grid/Action/pay.html.twig"
        filter:
            shop_string: "@SyliusShop/Grid/Filter/string.html.twig"
    grids:
        sylius_shop_account_order:
            fields:
                state:
                    type: twig
                    label: sylius.ui.state
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/label.html.twig"
                        vars:
                            labels: "@SyliusShop/Account/Order/Label/State"
            actions:
                item:
                    show:
                        type: shop_show
                        label: sylius.ui.show
                        options:
                            link:
                                route: sylius_shop_account_order_show
                                parameters:
                                    number: resource.number
                    pay:
                        type: shop_pay
                        label: sylius.ui.pay
                        options:
                            link:
                                route: sylius_shop_order_show
                                parameters:
                                    tokenValue: resource.tokenValue
